### PR TITLE
Add collisions comparison between PySDM and analytic solutions from Srivastava 1982

### PR DESCRIPTION
**Pull request by abulenok**
box model

### CODE REVIEW

**Comment by slayoo** [comment]
Let's write down our TODOs:
- [ ] breakup!
- [ ] include different initial conditions in the analysis
- code refactors:
  - [ ] `simulation.py` files (and class - to be used in smoke tests) 
  - [ ] `settings.py` files (and class - to be used in smoke tests) 
  - [ ] plotting logic - commons in a file that could be also used from the smoke tests
  - [ ] notebooks (also for the code reproducing analytic-only plots in the paper)
- [ ] smoke tests 
- [ ] smoke tests also on GPU
- [ ] ensemble analysis (same parameters, different seeds)
- [ ] hardcode seed to make plots reproduecible

**Comment by slayoo** [comment]
@abulenok 
- [ ] we need a new PR to PySDM and a pointer to it in `test-time-requirements.txt` here so that `ConstantSize` fragmentation is available
- [ ] the `appendix.ipynb` and all simulation-related files should go into `deJong_Mackay_2022` folder rather than `Srivastava_1982`
- [ ] let's add relevant colab/nbviewer/mybinder badges to the README file
- [ ] ditto in the notebook header
- [ ] our Colab magick in the first notebook cell is needed to make it executable on Colab:
```python
import sys
if 'google.colab' in sys.modules:
    !pip --quiet install open-atmos-jupyter-utils
    from open_atmos_jupyter_utils import pip_install_on_colab
    pip_install_on_colab('PySDM-examples')
```

**Comment by slayoo** [comment]
also, looking at the plots, I realise that it would likely be worth trying out plotting +/- standard deviation range instead of min/max - since we compare with mean-field SCE solutions, plotting outermost outliers brings little value here
- [ ] plot +/- stdev instead of min/max ranges

**Comment by slayoo** [comment]
- [ ] the frag_mass in plot title has a wrong unit - it is printed in "kg" but labelled as "g"

**Comment by slayoo** [comment]
@abulenok some more comments:
- [ ] the lower limit of the super-droplet-count plots is too high, it is hard to discern the blue line from the plot axis
- [ ] since we use mass of fragment to describe the settings, it's better to use mass instead of volume ration on the label of y axis of the volum-ratio plot
- [ ] probably worth to add a word "droplet" to the "total number" label to discern from super-droplet number
- [ ] the axi limits are likely better to be set using sigma than using min/max (merg+break middle plot limits look fishy now)

**Comment by slayoo** [comment]
- [ ] make rho 1000 kg / m**3 (from PySDM.physics import constants_defaults, constants_defaults.rho_w, pass to formulae)
- [ ] consider changing Settings.drop_mass_0 (so that the above change does not modify the setup)
- [ ] move all files (except Equations) to deJong
- [ ] all rates should be in 1/dv units ?
- [ ] smoke tests with asserts (n_realisations=2 if CI)
- [ ] notebook n_steps = 1 if CI
- [ ] move test_fig1 and test_eq_13_14 into a notebook (which would be the only notebook in Srivastava_1982 folder)
- [ ] unit tests for same effect of changing dt or c
- [ ] label GPU TODOs with #987

**Comment by slayoo** [comment]
- [ ] rerun notebooks to ensure that merged plot are consistent with the merged code

**Comment by abulenok** [comment]
- [ ] Check if it will work on GPU out of the box

**Review by slayoo — APPROVED** [review]

**Pull request merged**
